"""Add 64 Brazilian species metadata to species_info.json."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

br_species = {
    "abudefduf_saxatilis": {
        "nomeCientifico": "Abudefduf Saxatilis",
        "nomeComum": "Sargento",
        "familia": "pomacentridae",
        "descricao": "Peixe recifal listrado comum na costa brasileira.",
        "tamanho": "15-20 cm",
        "habitat": "Recifes de coral e costões rochosos",
        "alimentacao": "Algas, pequenos invertebrados, plâncton",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Suas listras verticais lembram galões militares, daí o nome sargento."
    },
    "acanthostracion_polygonium": {
        "nomeCientifico": "Acanthostracion Polygonium",
        "nomeComum": "Peixe-cofre",
        "familia": "ostraciidae",
        "descricao": "Peixe com corpo coberto por placas ósseas formando uma carapaça.",
        "tamanho": "15-30 cm",
        "habitat": "Recifes de coral e fundos rochosos",
        "alimentacao": "Esponjas, tunicados, invertebrados",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Libera toxina pela pele quando estressado."
    },
    "acanthurus_chirurgus": {
        "nomeCientifico": "Acanthurus Chirurgus",
        "nomeComum": "Cirurgião",
        "familia": "acanthuridae",
        "descricao": "Peixe herbívoro com espinho cortante na base da cauda.",
        "tamanho": "25-35 cm",
        "habitat": "Recifes de coral",
        "alimentacao": "Algas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "O espinho na cauda é afiado como um bisturi."
    },
    "acanthurus_coeruleus": {
        "nomeCientifico": "Acanthurus Coeruleus",
        "nomeComum": "Cirurgião-azul",
        "familia": "acanthuridae",
        "descricao": "Peixe azul vibrante dos recifes atlânticos.",
        "tamanho": "20-35 cm",
        "habitat": "Recifes de coral",
        "alimentacao": "Algas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Os juvenis são amarelos e vão ficando azuis ao crescer."
    },
    "aluterus_monoceros": {
        "nomeCientifico": "Aluterus Monoceros",
        "nomeComum": "Peixe-unicórnio",
        "familia": "monacanthidae",
        "descricao": "Peixe achatado lateralmente com espinho dorsal proeminente.",
        "tamanho": "40-60 cm",
        "habitat": "Águas costeiras e oceânicas",
        "alimentacao": "Algas, invertebrados, medusas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Pode mudar de cor para se camuflar."
    },
    "anisotremus_surinamensis": {
        "nomeCientifico": "Anisotremus Surinamensis",
        "nomeComum": "Sargo-de-beiço",
        "familia": "haemulidae",
        "descricao": "Peixe robusto com lábios grossos encontrado em recifes.",
        "tamanho": "30-50 cm",
        "habitat": "Recifes rochosos e naufrágios",
        "alimentacao": "Ouriços, crustáceos, moluscos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Importante na pesca esportiva subaquática."
    },
    "anisotremus_virginicus": {
        "nomeCientifico": "Anisotremus Virginicus",
        "nomeComum": "Salema",
        "familia": "haemulidae",
        "descricao": "Peixe colorido com faixas amarelas e azuis.",
        "tamanho": "20-35 cm",
        "habitat": "Recifes de coral e fundos rochosos",
        "alimentacao": "Invertebrados bentônicos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Emite sons grunhindo com os dentes faríngeos."
    },
    "arapaima_gigas": {
        "nomeCientifico": "Arapaima Gigas",
        "nomeComum": "Pirarucu",
        "familia": "arapaimidae",
        "descricao": "Maior peixe de escamas de água doce do mundo, ícone amazônico.",
        "tamanho": "200-300 cm",
        "habitat": "Rios e lagos da Amazônia",
        "alimentacao": "Peixes, crustáceos",
        "conservacao": "Dados insuficientes",
        "conservacao_detalhe": "Sobre-explorado historicamente, mas projetos de manejo sustentável têm recuperado populações.",
        "curiosidade": "Respira ar atmosférico e pode alcançar 200 kg. Suas escamas são resistentes a piranhas."
    },
    "astronotus_ocellatus": {
        "nomeCientifico": "Astronotus Ocellatus",
        "nomeComum": "Oscar / Apaiari",
        "familia": "cichlidae",
        "descricao": "Ciclídeo sul-americano popular em aquarismo e pesca esportiva.",
        "tamanho": "25-40 cm",
        "habitat": "Rios e lagos de água doce",
        "alimentacao": "Peixes pequenos, insetos, crustáceos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Reconhece seu dono e pode ser treinado a comer na mão."
    },
    "astyanax_lacustris": {
        "nomeCientifico": "Astyanax Lacustris",
        "nomeComum": "Lambari",
        "familia": "characidae",
        "descricao": "Pequeno peixe de água doce, muito comum em rios brasileiros.",
        "tamanho": "8-15 cm",
        "habitat": "Rios, riachos e lagoas",
        "alimentacao": "Onívoro — insetos, algas, sementes",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "É a isca viva mais utilizada na pesca esportiva no Brasil."
    },
    "balistes_capriscus": {
        "nomeCientifico": "Balistes Capriscus",
        "nomeComum": "Cangulo / Peixe-porco",
        "familia": "balistidae",
        "descricao": "Peixe com corpo oval e pele áspera como lixa.",
        "tamanho": "25-40 cm",
        "habitat": "Recifes e fundos rochosos",
        "alimentacao": "Ouriços, moluscos, crustáceos",
        "conservacao": "Vulnerável",
        "conservacao_detalhe": "Populações em declínio por sobrepesca.",
        "curiosidade": "Trava seu primeiro espinho dorsal como trava de gatilho."
    },
    "bathygobius_soporator": {
        "nomeCientifico": "Bathygobius Soporator",
        "nomeComum": "Amboré / Maria-da-toca",
        "familia": "gobiidae",
        "descricao": "Pequeno gobídeo que habita poças de maré.",
        "tamanho": "8-15 cm",
        "habitat": "Poças de maré e costões rochosos",
        "alimentacao": "Pequenos invertebrados e algas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Consegue sobreviver fora da água por curtos períodos."
    },
    "brycon_hilarii": {
        "nomeCientifico": "Brycon Hilarii",
        "nomeComum": "Piraputanga",
        "familia": "bryconidae",
        "descricao": "Peixe de água doce com nadadeiras vermelhas, popular na pesca esportiva.",
        "tamanho": "30-50 cm",
        "habitat": "Rios de águas claras do Pantanal e Cerrado",
        "alimentacao": "Frutas, sementes, insetos, peixes pequenos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Salta para pegar frutas das árvores nas margens dos rios."
    },
    "caranx_latus": {
        "nomeCientifico": "Caranx Latus",
        "nomeComum": "Xaréu",
        "familia": "carangidae",
        "descricao": "Peixe pelágico e veloz, apreciado na pesca esportiva.",
        "tamanho": "40-70 cm",
        "habitat": "Águas costeiras e recifes",
        "alimentacao": "Peixes pequenos e lulas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Forma cardumes que caçam cooperativamente."
    },
    "centropomus_undecimalis": {
        "nomeCientifico": "Centropomus Undecimalis",
        "nomeComum": "Robalo-flecha",
        "familia": "centropomidae",
        "descricao": "Predador costeiro de alto valor na pesca esportiva brasileira.",
        "tamanho": "50-100 cm",
        "habitat": "Estuários, manguezais, rios costeiros",
        "alimentacao": "Peixes, camarões, crustáceos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Muda de sexo — nasce macho e pode virar fêmea."
    },
    "chaetodipterus_faber": {
        "nomeCientifico": "Chaetodipterus Faber",
        "nomeComum": "Paru / Enxada",
        "familia": "ephippidae",
        "descricao": "Peixe comprimido lateralmente, lembra uma pá ou enxada.",
        "tamanho": "30-50 cm",
        "habitat": "Recifes, pilares de pontes, naufrágios",
        "alimentacao": "Invertebrados, medusas, crustáceos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Os juvenis se deitam de lado para imitar folhas mortas."
    },
    "chaetodon_striatus": {
        "nomeCientifico": "Chaetodon Striatus",
        "nomeComum": "Borboleta-listrado",
        "familia": "chaetodontidae",
        "descricao": "Peixe-borboleta com faixas verticais escuras.",
        "tamanho": "10-15 cm",
        "habitat": "Recifes de coral",
        "alimentacao": "Pólipos de coral, vermes, pequenos invertebrados",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Forma pares monogâmicos para a vida toda."
    },
    "chilomycterus_spinosus": {
        "nomeCientifico": "Chilomycterus Spinosus",
        "nomeComum": "Baiacu-de-espinho",
        "familia": "diodontidae",
        "descricao": "Peixe com espinhos fixos que infla quando ameaçado.",
        "tamanho": "15-30 cm",
        "habitat": "Recifes e fundos rochosos",
        "alimentacao": "Moluscos, ouriços, crustáceos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Seus espinhos permanecem eretos mesmo quando desinflado."
    },
    "cichla_kelberi": {
        "nomeCientifico": "Cichla Kelberi",
        "nomeComum": "Tucunaré-amarelo",
        "familia": "cichlidae",
        "descricao": "Tucunaré de coloração amarelada, introduzido em vários reservatórios do Brasil.",
        "tamanho": "30-45 cm",
        "habitat": "Reservatórios e lagos artificiais",
        "alimentacao": "Peixes pequenos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "Espécie invasora em muitas bacias hidrográficas.",
        "curiosidade": "Espécie descrita apenas em 2006."
    },
    "cichla_ocellaris": {
        "nomeCientifico": "Cichla Ocellaris",
        "nomeComum": "Tucunaré",
        "familia": "cichlidae",
        "descricao": "Predador de topo, um dos peixes mais cobiçados da pesca esportiva tropical.",
        "tamanho": "40-60 cm",
        "habitat": "Rios, lagos e reservatórios tropicais",
        "alimentacao": "Peixes pequenos, camarões",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "O macho desenvolve uma protuberância na cabeça durante a reprodução."
    },
    "cichla_temensis": {
        "nomeCientifico": "Cichla Temensis",
        "nomeComum": "Tucunaré-açu",
        "familia": "cichlidae",
        "descricao": "O maior dos tucunarés, troféu máximo da pesca esportiva amazônica.",
        "tamanho": "60-100 cm",
        "habitat": "Rios de águas negras e claras da Amazônia",
        "alimentacao": "Peixes",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Pode ultrapassar 12 kg. O turismo de pesca ao tucunaré-açu movimenta milhões na Amazônia."
    },
    "colossoma_macropomum": {
        "nomeCientifico": "Colossoma Macropomum",
        "nomeComum": "Tambaqui",
        "familia": "serrasalmidae",
        "descricao": "Maior caracídeo do mundo, fundamental na piscicultura e pesca amazônica.",
        "tamanho": "50-100 cm",
        "habitat": "Rios e várzeas da Amazônia",
        "alimentacao": "Frutas, sementes, zooplâncton",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "Abundante em cativeiro, mas populações selvagens sofrem pressão de pesca.",
        "curiosidade": "Tem dentes que lembram os humanos, adaptados para quebrar sementes duras."
    },
    "coptodon_rendalli": {
        "nomeCientifico": "Coptodon Rendalli",
        "nomeComum": "Tilápia-rendalli",
        "familia": "cichlidae",
        "descricao": "Tilápia africana introduzida no Brasil para aquicultura.",
        "tamanho": "20-35 cm",
        "habitat": "Lagos, represas e rios",
        "alimentacao": "Plantas aquáticas, algas, detritos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "Espécie invasora em muitos ecossistemas brasileiros.",
        "curiosidade": "Incuba os ovos na boca para proteger os filhotes."
    },
    "cyprinus_rubrofuscus": {
        "nomeCientifico": "Cyprinus Rubrofuscus",
        "nomeComum": "Carpa",
        "familia": "cyprinidae",
        "descricao": "Carpa asiática introduzida mundialmente, incluindo no Brasil.",
        "tamanho": "30-80 cm",
        "habitat": "Lagos, represas e rios calmos",
        "alimentacao": "Onívoro — insetos, plantas, moluscos",
        "conservacao": "Vulnerável (no habitat nativo)",
        "conservacao_detalhe": "",
        "curiosidade": "Cultivada há mais de 2.000 anos na China."
    },
    "dactylopterus_volitans": {
        "nomeCientifico": "Dactylopterus Volitans",
        "nomeComum": "Coió / Voador",
        "familia": "dactylopteridae",
        "descricao": "Peixe com nadadeiras peitorais enormes que se abrem como asas.",
        "tamanho": "25-40 cm",
        "habitat": "Fundos arenosos e rochosos costeiros",
        "alimentacao": "Crustáceos e moluscos do fundo",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Apesar do nome, não voa — usa as nadadeiras para assustar predadores."
    },
    "diplodus_argenteus": {
        "nomeCientifico": "Diplodus Argenteus",
        "nomeComum": "Marimbá",
        "familia": "sparidae",
        "descricao": "Peixe prateado comum nos costões rochosos brasileiros.",
        "tamanho": "15-25 cm",
        "habitat": "Costões rochosos e recifes",
        "alimentacao": "Algas, pequenos invertebrados, cracas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Muito procurado na pesca com vara nos costões."
    },
    "epinephelus_marginatus": {
        "nomeCientifico": "Epinephelus Marginatus",
        "nomeComum": "Garoupa-verdadeira",
        "familia": "serranidae",
        "descricao": "Grande predador recifal, muito valorizado na gastronomia.",
        "tamanho": "40-100 cm",
        "habitat": "Recifes rochosos e naufrágios",
        "alimentacao": "Peixes, polvos, crustáceos",
        "conservacao": "Vulnerável",
        "conservacao_detalhe": "Sobrepesca reduziu populações significativamente.",
        "curiosidade": "Hermafrodita protogínica — nasce fêmea e vira macho."
    },
    "geophagus_brasiliensis": {
        "nomeCientifico": "Geophagus Brasiliensis",
        "nomeComum": "Acará / Cará",
        "familia": "cichlidae",
        "descricao": "Ciclídeo nativo do Brasil, muito resistente e adaptável.",
        "tamanho": "15-25 cm",
        "habitat": "Rios, riachos e lagoas",
        "alimentacao": "Invertebrados do substrato, detritos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Mastiga o substrato para filtrar alimento — seu nome significa comedor de terra."
    },
    "geophagus_iporangensis": {
        "nomeCientifico": "Geophagus Iporangensis",
        "nomeComum": "Acará-de-Iporanga",
        "familia": "cichlidae",
        "descricao": "Ciclídeo endêmico da região de Iporanga, São Paulo.",
        "tamanho": "15-20 cm",
        "habitat": "Rios da bacia do Ribeira de Iguape",
        "alimentacao": "Invertebrados do substrato",
        "conservacao": "Dados insuficientes",
        "conservacao_detalhe": "",
        "curiosidade": "Espécie com distribuição muito restrita."
    },
    "gymnothorax_funebris": {
        "nomeCientifico": "Gymnothorax Funebris",
        "nomeComum": "Moreia-verde",
        "familia": "muraenidae",
        "descricao": "Grande moreia esverdeada encontrada em recifes tropicais.",
        "tamanho": "100-200 cm",
        "habitat": "Recifes de coral, tocas e fendas rochosas",
        "alimentacao": "Peixes, polvos, crustáceos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Caça à noite e pode ser agressiva se provocada."
    },
    "haemulon_aurolineatum": {
        "nomeCientifico": "Haemulon Aurolineatum",
        "nomeComum": "Cocoroca",
        "familia": "haemulidae",
        "descricao": "Peixe com listras amarelas encontrado em cardumes nos recifes.",
        "tamanho": "15-25 cm",
        "habitat": "Recifes de coral",
        "alimentacao": "Invertebrados bentônicos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Produz sons grunhindo com os dentes faríngeos."
    },
    "haemulon_parra": {
        "nomeCientifico": "Haemulon Parra",
        "nomeComum": "Cambuba",
        "familia": "haemulidae",
        "descricao": "Peixe de recife com padrão listrado característico.",
        "tamanho": "20-35 cm",
        "habitat": "Recifes e fundos rochosos",
        "alimentacao": "Crustáceos e vermes",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Muda dramaticamente de cor entre dia e noite."
    },
    "hippocampus_reidi": {
        "nomeCientifico": "Hippocampus Reidi",
        "nomeComum": "Cavalo-marinho",
        "familia": "syngnathidae",
        "descricao": "Cavalo-marinho de focinho longo, encontrado na costa brasileira.",
        "tamanho": "10-18 cm",
        "habitat": "Recifes, algas e gramas marinhas",
        "alimentacao": "Pequenos crustáceos (copépodes, artêmias)",
        "conservacao": "Quase ameaçado",
        "conservacao_detalhe": "Captura para aquarismo e medicina tradicional.",
        "curiosidade": "O macho é quem carrega os ovos e dá à luz os filhotes."
    },
    "holocentrus_adscensionis": {
        "nomeCientifico": "Holocentrus Adscensionis",
        "nomeComum": "Jaguareçá / Mariquita",
        "familia": "holocentridae",
        "descricao": "Peixe noturno de olhos grandes e coloração avermelhada.",
        "tamanho": "20-30 cm",
        "habitat": "Recifes de coral e tocas rochosas",
        "alimentacao": "Crustáceos nocturnos e pequenos peixes",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Fica escondido de dia e sai para caçar à noite."
    },
    "hoplerythrinus_unitaeniatus": {
        "nomeCientifico": "Hoplerythrinus Unitaeniatus",
        "nomeComum": "Jeju / Marobá",
        "familia": "erythrinidae",
        "descricao": "Peixe predador de água doce parente da traíra.",
        "tamanho": "20-30 cm",
        "habitat": "Águas rasas, alagados e brejos",
        "alimentacao": "Peixes pequenos, insetos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Respira ar atmosférico e pode se deslocar entre poças durante secas."
    },
    "hoplias_malabaricus": {
        "nomeCientifico": "Hoplias Malabaricus",
        "nomeComum": "Traíra",
        "familia": "erythrinidae",
        "descricao": "Predador voraz de água doce, um dos peixes mais comuns do Brasil.",
        "tamanho": "30-50 cm",
        "habitat": "Rios, lagos, lagoas e alagados",
        "alimentacao": "Peixes, camarões, insetos aquáticos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Conhecida pela mordida forte — tem dentes caninos impressionantes."
    },
    "hoplosternum_littorale": {
        "nomeCientifico": "Hoplosternum Littorale",
        "nomeComum": "Tamoatá / Tamboatá",
        "familia": "callichthyidae",
        "descricao": "Peixe blindado que constrói ninhos de bolha.",
        "tamanho": "15-25 cm",
        "habitat": "Águas rasas, brejos e alagados",
        "alimentacao": "Invertebrados do fundo, detritos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "O macho constrói um ninho de espuma flutuante para os ovos."
    },
    "leporinus_friderici": {
        "nomeCientifico": "Leporinus Friderici",
        "nomeComum": "Piau-três-pintas",
        "familia": "anostomidae",
        "descricao": "Peixe com três manchas escuras no corpo, comum em rios brasileiros.",
        "tamanho": "20-35 cm",
        "habitat": "Rios e corredeiras",
        "alimentacao": "Onívoro — frutas, sementes, insetos, algas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Realiza migrações reprodutivas chamadas piracemas."
    },
    "lugubria_lenticulata": {
        "nomeCientifico": "Lugubria Lenticulata",
        "nomeComum": "Jacundá-pinima",
        "familia": "cichlidae",
        "descricao": "Ciclídeo predador com padrão de cores vibrante.",
        "tamanho": "15-25 cm",
        "habitat": "Rios de águas claras e negras",
        "alimentacao": "Peixes pequenos, camarões",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Muito procurado por aquaristas pela beleza de suas cores."
    },
    "lutjanus_jocu": {
        "nomeCientifico": "Lutjanus Jocu",
        "nomeComum": "Dentão / Cioba",
        "familia": "lutjanidae",
        "descricao": "Peixe predador de recife com dentes caninos proeminentes.",
        "tamanho": "40-70 cm",
        "habitat": "Recifes de coral e fundos rochosos",
        "alimentacao": "Peixes, crustáceos, cefalópodes",
        "conservacao": "Quase ameaçado",
        "conservacao_detalhe": "",
        "curiosidade": "Seus grandes caninos são usados para capturar presas escorregadias."
    },
    "micropogonias_furnieri": {
        "nomeCientifico": "Micropogonias Furnieri",
        "nomeComum": "Corvina",
        "familia": "sciaenidae",
        "descricao": "Peixe costeiro muito pescado comercialmente no Brasil.",
        "tamanho": "30-60 cm",
        "habitat": "Fundos lamosos e arenosos costeiros",
        "alimentacao": "Crustáceos, vermes, moluscos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Produz sons usando a bexiga natatória — daí o nome corvina."
    },
    "mycteroperca_bonaci": {
        "nomeCientifico": "Mycteroperca Bonaci",
        "nomeComum": "Badejo",
        "familia": "serranidae",
        "descricao": "Grande predador de recife, valorizado na pesca e gastronomia.",
        "tamanho": "50-120 cm",
        "habitat": "Recifes rochosos e de coral",
        "alimentacao": "Peixes e lulas",
        "conservacao": "Quase ameaçado",
        "conservacao_detalhe": "Sobrepesca é uma preocupação crescente.",
        "curiosidade": "Pode viver mais de 30 anos."
    },
    "myrichthys_ocellatus": {
        "nomeCientifico": "Myrichthys Ocellatus",
        "nomeComum": "Mututuca / Enguia-pintada",
        "familia": "ophichthidae",
        "descricao": "Serpente-do-mar com manchas ocelares douradas.",
        "tamanho": "60-100 cm",
        "habitat": "Recifes e fundos arenosos",
        "alimentacao": "Crustáceos e moluscos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Não é venenosa apesar da aparência de cobra."
    },
    "oreochromis_niloticus": {
        "nomeCientifico": "Oreochromis Niloticus",
        "nomeComum": "Tilápia-do-nilo",
        "familia": "cichlidae",
        "descricao": "Peixe de aquicultura mais cultivado no Brasil e no mundo.",
        "tamanho": "20-40 cm",
        "habitat": "Lagos, represas, fazendas de piscicultura",
        "alimentacao": "Onívoro — algas, rações, detritos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "Espécie invasora em muitos ecossistemas.",
        "curiosidade": "O Brasil é o 3º maior produtor mundial de tilápia."
    },
    "osteoglossum_bicirrhosum": {
        "nomeCientifico": "Osteoglossum Bicirrhosum",
        "nomeComum": "Aruanã",
        "familia": "osteoglossidae",
        "descricao": "Peixe predador elegante da Amazônia com escamas brilhantes.",
        "tamanho": "60-100 cm",
        "habitat": "Rios e lagos amazônicos de águas calmas",
        "alimentacao": "Insetos, peixes, pequenos animais da superfície",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Salta até 1 metro fora da água para capturar insetos e até pássaros."
    },
    "piaractus_mesopotamicus": {
        "nomeCientifico": "Piaractus Mesopotamicus",
        "nomeComum": "Pacu",
        "familia": "serrasalmidae",
        "descricao": "Peixe de água doce muito apreciado na pesca e culinária.",
        "tamanho": "40-60 cm",
        "habitat": "Rios e alagados do Pantanal e bacia do Paraná",
        "alimentacao": "Frutas, sementes, vegetação aquática",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Tem dentes que lembram os molares humanos, adaptados para esmagar sementes."
    },
    "poecilia_reticulata": {
        "nomeCientifico": "Poecilia Reticulata",
        "nomeComum": "Guppy / Lebiste / Barrigudinho",
        "familia": "poeciliidae",
        "descricao": "Pequeno peixe colorido, um dos mais populares do aquarismo.",
        "tamanho": "3-6 cm",
        "habitat": "Riachos, valas e águas paradas",
        "alimentacao": "Larvas de mosquito, algas, microorganismos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Usado no controle biológico de dengue por comer larvas de mosquito."
    },
    "poecilia_vivipara": {
        "nomeCientifico": "Poecilia Vivipara",
        "nomeComum": "Guaru / Barrigudinho",
        "familia": "poeciliidae",
        "descricao": "Pequeno peixe vivíparo nativo do Brasil.",
        "tamanho": "3-7 cm",
        "habitat": "Rios, riachos, brejos e poças",
        "alimentacao": "Algas, larvas de insetos, detritos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "A fêmea dá à luz filhotes vivos, sem desovar."
    },
    "pomacanthus_paru": {
        "nomeCientifico": "Pomacanthus Paru",
        "nomeComum": "Paru / Frade",
        "familia": "pomacanthidae",
        "descricao": "Grande peixe-anjo negro com bordas douradas nas escamas.",
        "tamanho": "30-40 cm",
        "habitat": "Recifes de coral",
        "alimentacao": "Esponjas, tunicados, algas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Os juvenis são totalmente diferentes — pretos com faixas amarelas."
    },
    "prochilodus_lineatus": {
        "nomeCientifico": "Prochilodus Lineatus",
        "nomeComum": "Curimbatá / Curimba",
        "familia": "prochilodontidae",
        "descricao": "Peixe migratório fundamental para a ecologia dos rios brasileiros.",
        "tamanho": "30-50 cm",
        "habitat": "Rios e planícies de inundação",
        "alimentacao": "Detritos orgânicos, algas e lodo",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Suas migrações (piracema) podem percorrer centenas de quilômetros."
    },
    "pseudupeneus_maculatus": {
        "nomeCientifico": "Pseudupeneus Maculatus",
        "nomeComum": "Trilha / Salmonete-pintado",
        "familia": "mullidae",
        "descricao": "Peixe com barbilhões e manchas escuras no corpo.",
        "tamanho": "15-25 cm",
        "habitat": "Recifes e fundos arenosos",
        "alimentacao": "Invertebrados do substrato",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Usa os barbilhões como sensores para encontrar alimento enterrado na areia."
    },
    "pterygoplichthys_ambrosettii": {
        "nomeCientifico": "Pterygoplichthys Ambrosettii",
        "nomeComum": "Cascudo",
        "familia": "loricariidae",
        "descricao": "Peixe blindado com ventosa bucal que raspa superfícies.",
        "tamanho": "30-50 cm",
        "habitat": "Rios e represas de água doce",
        "alimentacao": "Algas, detritos, restos orgânicos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Pode sobreviver fora da água por horas respirando ar."
    },
    "pygocentrus_nattereri": {
        "nomeCientifico": "Pygocentrus Nattereri",
        "nomeComum": "Piranha-vermelha",
        "familia": "serrasalmidae",
        "descricao": "A espécie de piranha mais conhecida, famosa por seus ataques em grupo.",
        "tamanho": "20-35 cm",
        "habitat": "Rios e lagos da América do Sul",
        "alimentacao": "Peixes, insetos, crustáceos, carniça",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Apesar da fama, ataques a humanos são raros e geralmente durante secas extremas."
    },
    "salminus_brasiliensis": {
        "nomeCientifico": "Salminus Brasiliensis",
        "nomeComum": "Dourado",
        "familia": "bryconidae",
        "descricao": "O rei dos rios brasileiros — predador dourado e poderoso, troféu máximo da pesca esportiva.",
        "tamanho": "50-100 cm",
        "habitat": "Rios de corredeiras e cachoeiras das bacias do Paraná, Paraguai e São Francisco",
        "alimentacao": "Peixes (principalmente piaus, lambaris e tuviras)",
        "conservacao": "Quase ameaçado",
        "conservacao_detalhe": "Barragens hidrelétricas prejudicam suas rotas migratórias.",
        "curiosidade": "Pode pesar mais de 25 kg e é chamado de salmão brasileiro pela sua coloração dourada brilhante e saltos espetaculares."
    },
    "serrasalmus_maculatus": {
        "nomeCientifico": "Serrasalmus Maculatus",
        "nomeComum": "Piranha",
        "familia": "serrasalmidae",
        "descricao": "Piranha com pintas escuras no corpo prateado.",
        "tamanho": "15-25 cm",
        "habitat": "Rios e lagoas de água doce",
        "alimentacao": "Peixes, nadadeiras de outros peixes",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Além de predadora, é lepidófaga — come escamas de outros peixes."
    },
    "sphoeroides_camila": {
        "nomeCientifico": "Sphoeroides Camila",
        "nomeComum": "Baiacu-brasileiro",
        "familia": "tetraodontidae",
        "descricao": "Baiacu endêmico da costa brasileira.",
        "tamanho": "10-20 cm",
        "habitat": "Águas costeiras rasas",
        "alimentacao": "Moluscos, crustáceos, algas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Infla o corpo engolindo água quando se sente ameaçado."
    },
    "sphoeroides_greeleyi": {
        "nomeCientifico": "Sphoeroides Greeleyi",
        "nomeComum": "Baiacu-verde",
        "familia": "tetraodontidae",
        "descricao": "Baiacu esverdeado comum em estuários brasileiros.",
        "tamanho": "10-18 cm",
        "habitat": "Estuários e manguezais",
        "alimentacao": "Moluscos, crustáceos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Possui tetrodotoxina, uma das toxinas mais potentes da natureza."
    },
    "sphoeroides_testudineus": {
        "nomeCientifico": "Sphoeroides Testudineus",
        "nomeComum": "Baiacu-pintado",
        "familia": "tetraodontidae",
        "descricao": "Baiacu com padrão xadrez marrom.",
        "tamanho": "15-30 cm",
        "habitat": "Estuários, manguezais e águas costeiras",
        "alimentacao": "Moluscos, cracas, ouriços",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Pode tolerar variações extremas de salinidade."
    },
    "stegastes_fuscus": {
        "nomeCientifico": "Stegastes Fuscus",
        "nomeComum": "Donzela / Castanheta",
        "familia": "pomacentridae",
        "descricao": "Peixe territorial que defende agressivamente seu território em recifes.",
        "tamanho": "10-15 cm",
        "habitat": "Recifes e costões rochosos",
        "alimentacao": "Algas que cultiva em seu território",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "É um dos poucos peixes que faz agricultura — cultiva um jardim de algas."
    },
    "stegastes_rocasensis": {
        "nomeCientifico": "Stegastes Rocasensis",
        "nomeComum": "Donzela-de-rocas",
        "familia": "pomacentridae",
        "descricao": "Espécie endêmica do Atol das Rocas e Fernando de Noronha.",
        "tamanho": "8-12 cm",
        "habitat": "Recifes do Atlântico Sul brasileiro",
        "alimentacao": "Algas",
        "conservacao": "Vulnerável",
        "conservacao_detalhe": "Distribuição muito restrita.",
        "curiosidade": "Só existe nessas duas localidades no mundo!"
    },
    "stegastes_variabilis": {
        "nomeCientifico": "Stegastes Variabilis",
        "nomeComum": "Donzela-do-cacau",
        "familia": "pomacentridae",
        "descricao": "Donzela de coloração variável, endêmica do Brasil.",
        "tamanho": "8-12 cm",
        "habitat": "Recifes rochosos e de coral",
        "alimentacao": "Algas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Muda de cor conforme o ambiente."
    },
    "steindachneridion_melanodermatum": {
        "nomeCientifico": "Steindachneridion Melanodermatum",
        "nomeComum": "Surubim-do-Iguaçu",
        "familia": "pimelodidae",
        "descricao": "Grande bagre endêmico do rio Iguaçu.",
        "tamanho": "50-80 cm",
        "habitat": "Rios de corredeiras e poções profundos",
        "alimentacao": "Peixes e crustáceos",
        "conservacao": "Em perigo",
        "conservacao_detalhe": "Endêmico de uma região com várias barragens.",
        "curiosidade": "Uma das espécies mais ameaçadas de peixes de água doce do Brasil."
    },
    "synbranchus_marmoratus": {
        "nomeCientifico": "Synbranchus Marmoratus",
        "nomeComum": "Mussum",
        "familia": "synbranchidae",
        "descricao": "Peixe serpentiforme que vive em brejos e pode se enterrar na lama.",
        "tamanho": "50-100 cm",
        "habitat": "Brejos, alagados, valas e rios rasos",
        "alimentacao": "Peixes pequenos, camarões, insetos",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Sobrevive fora da água enterrado na lama durante secas."
    },
    "trichiurus_lepturus": {
        "nomeCientifico": "Trichiurus Lepturus",
        "nomeComum": "Espada / Peixe-espada",
        "familia": "trichiuridae",
        "descricao": "Peixe prateado e alongado como uma fita reluzente.",
        "tamanho": "80-150 cm",
        "habitat": "Águas costeiras e oceânicas",
        "alimentacao": "Peixes pequenos e lulas",
        "conservacao": "Pouco preocupante",
        "conservacao_detalhe": "",
        "curiosidade": "Seu corpo prateado reflete a luz como uma espada."
    },
}

with open(ROOT / "species_info.json", encoding="utf-8") as f:
    info = json.load(f)

info.update(br_species)

with open(ROOT / "species_info.json", "w", encoding="utf-8") as f:
    json.dump(info, f, ensure_ascii=False, indent=2)

print(f"Added {len(br_species)} Brazilian species. Total entries: {len(info)}")

with open(ROOT / "datasets" / "unified" / "label_map.json", encoding="utf-8") as f:
    lm = json.load(f)
model_keys = set(lm.get("label_to_idx", lm.get("class_to_idx", {})).keys())
covered = model_keys & set(info.keys())
print(f"Model coverage: {len(covered)} / {len(model_keys)}")
missing = model_keys - set(info.keys())
if missing:
    print(f"Still missing: {sorted(missing)}")
else:
    print("All model classes have metadata!")
